version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mentorize
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - pg_network

  mentorize-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    networks:
      - pg_network

  mentorize-front:
    image: node:latest
    volumes:
      - ./your_app_directory:/app
    working_dir: /app
    command: >
      sh -c "if [ -d 'mentorize-frontend' ]; then rm -rf mentorize-frontend; fi && git clone https://github.com/Hack-for-Change/mentorize-frontend.git && cd mentorize-frontend && npm install && npm start"

    ports:
      - "3000:3000"
    networks:
      - pg_network

networks:
  pg_network:
    driver: bridge
